#ifndef GC_CONFIG_H_HEADER
#define GC_CONFIG_H_HEADER

#define GC_THREAD_LOCAL_SEMISPACE_SIZE      0x100000
#define GC_COLLECT_ON_ALLOCATION_FAILURE    1
//#define GC_DEBUG

#endif // GC_CONFIG_H_HEADER
